### ISSUE TITLE
I'm unable to start Ultimate RVC.

### ISSUE THREAD

**Issue by SokolyMoravia** [JackismyShephard/ultimate-rvc#67] opened 2024-07-26 09:34 UTC
I believed that I did every step correctly: Install the latest edition of Git, then clone the Ultimate RVC repository and install dependencies on the Git command board. Once I saw the message "Ultimate RVC has been successfully installed!" popping up on the Git command board, I pasted the code ./urvc.bat run to start the app, but for some reasons I can't start it, with the message "The system cannot find the path specified". How do I fix this?
![bandicam 2024-07-26 16-21-05-530](https://github.com/user-attachments/assets/70528d88-0177-4184-8f8a-786cd7d035e9)
![bandicam 2024-07-26 16-21-10-455](https://github.com/user-attachments/assets/e85f1a9d-a49a-4301-a366-e6d8305664e2)

**Comment by JackismyShephard** [comment] 2024-07-26 15:43
Hi @SokolyMoravia. 

Thank you for reaching out.  I think the problem is due to you running `urvc.bat` in a unix terminal emulator rather than powershell or command prompt. Try and do that instead and let me know how it goes :blush:

**Comment by JackismyShephard** [comment] 2024-08-31 17:39
I will close this issue now but you are free to reach out again if you have problems @SokolyMoravia

**Closed** 2024-08-31 17:39 UTC
